apiVersion: v1
kind: Service
metadata:
  name: eum-web
  namespace: eum
  labels:
    app.kubernetes.io/name: eum-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eum-web
  ports:
    - name: http
      port: 80
      targetPort: http
